const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),cp=require('node:child_process');
const bank=require('../assets/phrase-bank.js'),groups=bank.filter(g=>g.items.every(q=>q.question));
function boot(values=new Map()){
 const nodes=new Map(),handlers={};const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',addEventListener:(name,fn)=>handlers[name]=fn});return nodes.get(id);};const spoken=[];
 const c={document:{querySelector:node,addEventListener(){}},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},addEventListener(){},location:{search:''},URLSearchParams,speechSynthesis:{cancel(){},getVoices:()=>[],speak:u=>spoken.push(u)},SpeechSynthesisUtterance:function(text){this.text=text;}};c.window=c;vm.createContext(c);for(const f of ['assets/phrase-bank.js','assets/conversation-practice.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);
 return{values,spoken,html:()=>node('#roleApp').innerHTML,click:(role,id)=>handlers.click({target:{closest:()=>({dataset:{role,id}})}}),change:value=>handlers.change({target:{id:'speechRate',value}})};
}
test('new 36 conversational exchanges are complete and 478 previous entries are preserved',()=>{assert.equal(groups.length,6);for(const g of groups)for(const q of g.items){for(const k of ['scene','question','questionJa','hint','en'])assert.ok(q[k]);assert.equal(q.prompt.replace('____',q.answer),q.en);}const parse=s=>JSON.parse(s.match(/const DATA=(\{.*?\}),W=DATA.words/s)[1]).words;const before=parse(cp.execFileSync('git',['show','56c6cc2c7542a9d32683b27275ef4302c298f38d:legacy.html'],{encoding:'utf8'}));assert.deepEqual(parse(fs.readFileSync('legacy.html','utf8')).slice(0,478),before);});
test('every role-play asks a teacher question and reveals a model only on request',()=>{const h=boot();for(const g of groups){h.click('start',g.id);for(const q of g.items){h.click('said');assert.equal(h.values.has('eigo305-conversation-self-v1')||h.html().includes('自己チェック'),true);h.click('teacher');assert.equal(h.spoken.at(-1).text,q.question);h.click('model');assert.equal(h.spoken.at(-1).text,q.question);h.click('reveal');h.click('model');assert.equal(h.spoken.at(-1).text,q.en);h.click('said');}assert.match(h.html(),/6回/);}const record=JSON.parse(h.values.get('eigo305-conversation-self-v1'));assert.equal(Object.keys(record).length,36);assert.equal(h.values.has('eigo305-mastered-v1'),false);});
test('self-check retry and speech speed persist appropriately without modifying learning sessions',()=>{const values=new Map([['eigo305-phrase-mission-v1','old-session'],['eigo305-mastered-v1','["pronoun-1"]']]);let h=boot(values);h.click('start',groups[0].id);h.change('0.65');h.click('teacher');assert.equal(h.spoken.at(-1).rate,.65);h.click('reveal');h.click('again');h=boot(values);h.click('weak');h.click('teacher');assert.equal(h.spoken.at(-1).text,groups[0].items[0].question);h.click('reveal');h.click('said');assert.equal(JSON.parse(values.get('eigo305-conversation-self-v1'))[groups[0].items[0].id],'said');assert.equal(values.get('eigo305-phrase-mission-v1'),'old-session');assert.equal(values.get('eigo305-mastered-v1'),'["pronoun-1"]');});
