const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),cp=require('node:child_process');
const groups=require('../assets/phrase-bank.js'),all=groups.flatMap(g=>g.items);
function boot(values=new Map()){
 const nodes=new Map(),listeners=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',addEventListener:(name,fn)=>listeners.set(id+name,fn)});return nodes.get(id);};
 const c={document:{querySelector:node,addEventListener(){}},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},addEventListener(){},console};c.window=c;vm.createContext(c);for(const f of ['assets/phrase-bank.js','assets/learning-progress.js','assets/phrase-mission.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);
 const click=(a,id)=>listeners.get('#appclick')({target:{closest:()=>({disabled:false,dataset:{a,id}})}});
 const state=()=>JSON.parse(values.get('eigo305-phrase-mission-v1'));
 function fill(wrong=false){const s=state();s.session.ids.forEach((id,i)=>{click('slot',String(i));const cards=[...node('#app').innerHTML.matchAll(/data-a="card" data-id="(\d+)">([^<]*)<\/button>/g)];const q=all.find(q=>q.id===id),decode=x=>x.replace(/&#39;/g,"'");const chosen=cards.find(x=>wrong&&i===0?decode(x[2])!==q.answer:decode(x[2])===q.answer);assert.ok(chosen);click('card',chosen[1]);});}
 return {values,click,state,fill,html:()=>node('#app').innerHTML};
}
test('72 phrases round-trip gaps and appear in both existing vocabulary and mission categories',()=>{const data=JSON.parse(fs.readFileSync('legacy.html','utf8').match(/const DATA=(\{.*?\}),W=DATA.words/s)[1]);assert.equal(all.length,72);assert.equal(new Set(all.map(q=>q.id)).size,72);for(const g of groups){assert.equal(g.items.length,6);assert.ok(fs.readFileSync('hayamihyo.html','utf8').includes(g.id));for(const q of g.items){assert.equal(q.prompt.replace('____',q.answer),q.en);assert.ok(data.words.some(w=>w.id===q.id&&w.en===q.en));}}});
test('all twelve missions can complete and collect exactly one stamp each',()=>{const h=boot();for(const g of groups){h.click('begin',g.id);h.fill();h.click('grade');assert.equal(h.state().session.first,6);h.click('complete');}assert.equal(h.state().stamps.length,12);h.click('begin',groups[0].id);h.fill();h.click('grade');assert.equal(h.state().stamps.length,12);});
test('incomplete grading is blocked, wrong-only retry and first score survive reload',()=>{let h=boot();h.click('begin',groups[0].id);h.click('grade');assert.equal(h.state().session.graded,false);h.fill(true);h.click('grade');assert.equal(h.state().session.first,5);h=boot(h.values);h.click('resume');h.click('retry');assert.equal(h.state().session.ids.length,1);assert.ok((h.html().match(/data-a="card"/g)||[]).length>=4);h.fill();h.click('grade');assert.equal(h.state().session.first,5);assert.equal(h.state().stamps.length,1);const progress=JSON.parse(h.values.get('eigo305-practice-v1'));assert.equal(Object.keys(progress['phrase-gap']).length,6);assert.equal(h.values.has('eigo305-mastered-v1'),false);});
test('original 442 entries remain byte-equivalent as data',()=>{const previous=cp.execFileSync('git',['show','HEAD:legacy.html'],{encoding:'utf8'});const parse=s=>JSON.parse(s.match(/const DATA=(\{.*?\}),W=DATA.words/s)[1]).words;assert.deepEqual(parse(fs.readFileSync('legacy.html','utf8')).slice(0,442),parse(previous).slice(0,442));});
