const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../assets/speaking-lab-core.js');
function boot(values=new Map()){
 const nodes=new Map(),handlers={};function node(id){if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',addEventListener:(name,fn)=>handlers[name]=fn});return nodes.get(id);}
 const spoken=[];const c={document:{querySelector:node,addEventListener(){}},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},addEventListener(){},speechSynthesis:{cancel(){},getVoices:()=>[],speak:u=>spoken.push(u)},SpeechSynthesisUtterance:function(text){this.text=text;}};c.window=c;vm.createContext(c);for(const file of ['assets/speaking-lab-core.js','assets/speaking-lab.js'])vm.runInContext(fs.readFileSync(file,'utf8'),c);
 return{values,spoken,html:()=>node('#labApp').innerHTML,click:(lab,id,slot)=>handlers.click({target:{closest:()=>({dataset:{lab,id,slot}})}}),state:()=>JSON.parse(values.get(C.KEY))};
}
test('all 15 missions generate complete English for each choice, including repeated slots',()=>{assert.equal(C.items.length,15);for(const q of C.items){if(!q.slots.length)assert.equal(C.sentence(q,[]),q.template);q.slots.forEach((slot,i)=>slot.forEach((option,j)=>{const picks=q.slots.map(()=>0);picks[i]=j;assert.ok(!C.sentence(q,picks).includes('{'));assert.ok(!C.sentence(q,picks).includes('____'));}));}const q=C.map.get('ask-sport');assert.equal(C.sentence(q,[1]),'I can play tennis. Can you play tennis?');});
test('all activities move from filled sentence to hidden recall to saved self-report',()=>{const h=boot();for(const t of C.themes){h.click('topic',t.id);for(const q of t.items){if(q.slots.length){h.click('next');assert.equal(h.state().session.index,t.items.indexOf(q));q.slots.forEach((_,i)=>h.click('choose','0',String(i)));}h.click('said');assert.equal(h.state().records[q.id]?.said??false,false);h.click('listen');assert.equal(h.spoken.at(-1).text,C.sentence(q,q.slots.map(()=>0)));h.click('hide');assert.ok(!h.html().includes('class="lab-card-list"'));h.click('said');assert.equal(h.state().records[q.id].said,true);h.click('next');}assert.equal(h.state().session,null);}assert.equal(Object.values(h.state().records).filter(r=>r.said).length,15);assert.equal(h.values.size,1);});
test('real-lesson use is manual, can be undone, and changing words resets the relevant milestone only',()=>{let h=boot();h.click('topic','swap');h.click('choose','0','0');h.click('hide');h.click('said');h.click('log');assert.equal(h.state().records['swap-like'].used,false);h.click('used','swap-like');assert.equal(h.state().records['swap-like'].used,true);h=boot(h.values);h.click('log');assert.match(h.html(),/先生に使えた（取り消す）/);h.click('used','swap-like');assert.equal(h.state().records['swap-like'].used,false);h.click('home');h.click('resume');h.click('choose','1','0');assert.equal(h.state().records['swap-like'].said,false);assert.equal(h.state().records['swap-like'].used,false);});
test('invalid stored choices and session are rejected while valid earlier milestones survive',()=>{const s=C.validate({version:1,records:{'swap-like':{picks:[90],said:true,used:true},'echo-again':{picks:[],said:true}},session:{theme:'swap',index:99}});assert.equal(s.records['swap-like'].said,false);assert.equal(s.records['echo-again'].said,true);assert.equal(s.session,null);});
